import { createFileRoute,useNavigate } from "@tanstack/react-router";
import { useEffect,useMemo,useRef,useState } from "react";
import { useDuel } from "@/lib/duel/provider";import { MatchBalance } from "@/components/duel/MatchBalance";import { OpponentOutBanner } from "@/components/duel/OpponentOutBanner";import { sfx } from "@/lib/duel/audio";import { createRng } from "@/lib/duel/engine/rhythm";import { simulateStackOpponent } from "@/lib/duel/engine/casual";
export const Route=createFileRoute("/play/stack")({component:Stack});
function Stack(){const nav=useNavigate(),{activeMatch,finishSurvivalMatch,ready,profile,wagerEur}=useDuel();const [score,setScore]=useState(0),[width,setWidth]=useState(72),[x,setX]=useState(14),[dir,setDir]=useState(1),[over,setOver]=useState(false);const last=useRef(0),raf=useRef<number|null>(null),xRef=useRef(14),dirRef=useRef(1),widthRef=useRef(72),scoreRef=useRef(0),baseX=useRef(14),done=useRef(false);const seed=activeMatch?.seed??1,bot=useMemo(()=>activeMatch?simulateStackOpponent(seed,activeMatch.opponent):0,[seed,activeMatch]),rng=useMemo(()=>createRng(seed),[seed]);
useEffect(()=>{if(ready&&!activeMatch)nav({to:"/"});},[ready,activeMatch,nav]);useEffect(()=>{if(!activeMatch)return;last.current=performance.now();const tick=(t:number)=>{const dt=Math.min(.04,(t-last.current)/1000);last.current=t;let nx=xRef.current+dirRef.current*(38+Math.min(70,scoreRef.current*3.2))*dt;if(nx<=0){nx=0;dirRef.current=1}else if(nx+widthRef.current>=100){nx=100-widthRef.current;dirRef.current=-1}xRef.current=nx;setX(nx);setDir(dirRef.current);raf.current=requestAnimationFrame(tick)};raf.current=requestAnimationFrame(tick);return()=>{if(raf.current)cancelAnimationFrame(raf.current)}},[activeMatch]);
if(!activeMatch)return null;const end=()=>{if(done.current)return;done.current=true;setOver(true);if(raf.current)cancelAnimationFrame(raf.current);sfx.miss();const o=finishSurvivalMatch({playerScore:scoreRef.current,opponentScore:bot});setTimeout(()=>{if(o){o.won?sfx.win():sfx.lose();nav({to:"/result"})}},650)};
const drop=()=>{if(done.current)return;const left=Math.max(xRef.current,baseX.current),right=Math.min(xRef.current+widthRef.current,baseX.current+widthRef.current),overlap=right-left;if(overlap<=1){end();return}scoreRef.current++;setScore(scoreRef.current);if(overlap>widthRef.current*.94){sfx.go()}else{sfx.tap();widthRef.current=overlap;baseX.current=left;setWidth(overlap)}xRef.current=dirRef.current>0?0:100-widthRef.current;setX(xRef.current);if(scoreRef.current>=100)end()};
return <main className="mx-auto flex h-[100dvh] w-full max-w-md touch-none select-none flex-col overflow-hidden bg-background"><MatchBalance coins={profile.coins} wagerEur={wagerEur}/><div className="flex justify-between px-5 py-2 text-xs"><b>STACK · {score}</b><span>vs {activeMatch.opponent.username}</span></div><section onPointerDown={drop} className="relative min-h-0 flex-1 overflow-hidden bg-card"><OpponentOutBanner opponentName={activeMatch.opponent.username} opponentScore={bot} playerScore={score} wagerEur={wagerEur} outAfterMs={Math.max(1600,bot*720)} label="blocks"/><div className="absolute inset-x-4 bottom-8 top-16 flex flex-col-reverse items-center gap-[2px] overflow-hidden">{Array.from({length:Math.min(score,18)}).map((_,i)=><div key={i} className="h-4 shrink-0 rounded-sm bg-primary/70" style={{width:`${width}%`}}/>)}</div><div className="absolute h-5 rounded bg-primary shadow-lg" style={{left:`${x}%`,width:`${width}%`,bottom:`calc(2rem + ${Math.min(score,18)*18}px)`}}/><p className="absolute bottom-2 inset-x-0 text-center text-xs text-muted-foreground">{over?"MISSED":"TAP TO DROP · PERFECT DROPS KEEP YOUR WIDTH"}</p></section></main>}
