import { createFileRoute,useNavigate } from "@tanstack/react-router";
import { useEffect,useMemo,useRef,useState } from "react";
import { useDuel } from "@/lib/duel/provider"; import { MatchBalance } from "@/components/duel/MatchBalance";
import { sfx,startMusic } from "@/lib/duel/audio"; import { createObstacleFeed,simulateSurvivalOpponent } from "@/lib/duel/engine/survival";
export const Route=createFileRoute("/play/flappy")({component:Flappy});
function Flappy(){const nav=useNavigate(),{activeMatch,finishSurvivalMatch,ready,profile,wagerEur}=useDuel();const [y,setY]=useState(50),[score,setScore]=useState(0),[scroll,setScroll]=useState(0);const yr=useRef(50),v=useRef(0),sr=useRef(0),sc=useRef(0),done=useRef(false),raf=useRef<number|null>(null),last=useRef(0);const seed=activeMatch?.seed??1,feed=useMemo(()=>createObstacleFeed(seed),[seed]),bot=useMemo(()=>activeMatch?simulateSurvivalOpponent(seed,activeMatch.opponent,"flappy"):0,[seed,activeMatch]);useEffect(()=>startMusic("flappy"),[]);useEffect(()=>{if(ready&&!activeMatch)nav({to:"/"});},[ready,activeMatch,nav]);
const end=()=>{if(done.current)return;done.current=true;if(raf.current)cancelAnimationFrame(raf.current);sfx.miss();const o=finishSurvivalMatch({playerScore:sc.current,opponentScore:bot});setTimeout(()=>{if(o){o.won?sfx.win():sfx.lose();nav({to:"/result"});}else nav({to:"/"});},850);};
useEffect(()=>{if(!activeMatch)return;last.current=performance.now();const tick=(now:number)=>{const dt=Math.min(.035,(now-last.current)/1000);last.current=now;v.current+=66*dt;yr.current+=v.current*dt;sr.current+=24*dt;let passed=0;for(const o of feed){const x=o.x-sr.current;if(x<24)passed++;if(x>19&&x<30&&(yr.current<o.gapY-o.gap/2||yr.current>o.gapY+o.gap/2)){end();return;}}sc.current=passed;setScore(passed);setY(yr.current);setScroll(sr.current);if(yr.current<2||yr.current>96){end();return;}raf.current=requestAnimationFrame(tick);};raf.current=requestAnimationFrame(tick);return()=>{if(raf.current)cancelAnimationFrame(raf.current);};},[activeMatch]);
if(!activeMatch)return null;const flap=()=>{if(!done.current){v.current=-31;sfx.tap();}};return <main onPointerDown={flap} className="mx-auto flex h-[100dvh] w-full max-w-md touch-none select-none flex-col overflow-hidden bg-background"><MatchBalance coins={profile.coins} wagerEur={wagerEur}/><div className="flex justify-between px-5 py-2 text-xs"><b>FLAPPY · {score}</b><span className="text-muted-foreground">vs {activeMatch.opponent.username}</span></div><section className="relative min-h-0 flex-1 overflow-hidden border-y border-border bg-card"><div className="absolute left-[24%] text-3xl" style={{top:`${y}%`}}>🐤</div>{feed.filter(o=>o.x-scroll>-15&&o.x-scroll<120).map(o=>{const x=o.x-scroll;return <div key={o.index}><span className="absolute top-0 bg-primary" style={{left:`${x}%`,width:`${o.size}%`,height:`${o.gapY-o.gap/2}%`}}/><span className="absolute bottom-0 bg-primary" style={{left:`${x}%`,width:`${o.size}%`,height:`${100-o.gapY-o.gap/2}%`}}/></div>})}<p className="absolute bottom-4 inset-x-0 text-center text-xs text-muted-foreground">TAP TO FLAP</p></section></main>;}
