/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as GamesRouteImport } from './routes/games'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as MatchRouteImport } from './routes/match'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as ResultRouteImport } from './routes/result'
import { Route as ChallengeCodeRouteImport } from './routes/challenge.$code'
import { Route as PlayDashRouteImport } from './routes/play.dash'
import { Route as PlayDirectionRouteImport } from './routes/play.direction'
import { Route as PlayFlappyRouteImport } from './routes/play.flappy'
import { Route as PlayKnifeRouteImport } from './routes/play.knife'
import { Route as PlayMemoryRouteImport } from './routes/play.memory'
import { Route as PlayPenaltyRouteImport } from './routes/play.penalty'
import { Route as PlayPrecisionRouteImport } from './routes/play.precision'
import { Route as PlayReactionRouteImport } from './routes/play.reaction'
import { Route as PlayRhythmRouteImport } from './routes/play.rhythm'
import { Route as PlayStackRouteImport } from './routes/play.stack'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const GamesRoute = GamesRouteImport.update({
  id: '/games',
  path: '/games',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const MatchRoute = MatchRouteImport.update({
  id: '/match',
  path: '/match',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultRoute = ResultRouteImport.update({
  id: '/result',
  path: '/result',
  getParentRoute: () => rootRouteImport,
} as any)
const ChallengeCodeRoute = ChallengeCodeRouteImport.update({
  id: '/challenge/$code',
  path: '/challenge/$code',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDashRoute = PlayDashRouteImport.update({
  id: '/play/dash',
  path: '/play/dash',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayDirectionRoute = PlayDirectionRouteImport.update({
  id: '/play/direction',
  path: '/play/direction',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayFlappyRoute = PlayFlappyRouteImport.update({
  id: '/play/flappy',
  path: '/play/flappy',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayKnifeRoute = PlayKnifeRouteImport.update({
  id: '/play/knife',
  path: '/play/knife',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayMemoryRoute = PlayMemoryRouteImport.update({
  id: '/play/memory',
  path: '/play/memory',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPenaltyRoute = PlayPenaltyRouteImport.update({
  id: '/play/penalty',
  path: '/play/penalty',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayPrecisionRoute = PlayPrecisionRouteImport.update({
  id: '/play/precision',
  path: '/play/precision',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayReactionRoute = PlayReactionRouteImport.update({
  id: '/play/reaction',
  path: '/play/reaction',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayRhythmRoute = PlayRhythmRouteImport.update({
  id: '/play/rhythm',
  path: '/play/rhythm',
  getParentRoute: () => rootRouteImport,
} as any)
const PlayStackRoute = PlayStackRouteImport.update({
  id: '/play/stack',
  path: '/play/stack',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/challenge/$code': typeof ChallengeCodeRoute
  '/play/dash': typeof PlayDashRoute
  '/play/direction': typeof PlayDirectionRoute
  '/play/flappy': typeof PlayFlappyRoute
  '/play/knife': typeof PlayKnifeRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/penalty': typeof PlayPenaltyRoute
  '/play/precision': typeof PlayPrecisionRoute
  '/play/reaction': typeof PlayReactionRoute
  '/play/rhythm': typeof PlayRhythmRoute
  '/play/stack': typeof PlayStackRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/challenge/$code': typeof ChallengeCodeRoute
  '/play/dash': typeof PlayDashRoute
  '/play/direction': typeof PlayDirectionRoute
  '/play/flappy': typeof PlayFlappyRoute
  '/play/knife': typeof PlayKnifeRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/penalty': typeof PlayPenaltyRoute
  '/play/precision': typeof PlayPrecisionRoute
  '/play/reaction': typeof PlayReactionRoute
  '/play/rhythm': typeof PlayRhythmRoute
  '/play/stack': typeof PlayStackRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/games': typeof GamesRoute
  '/leaderboard': typeof LeaderboardRoute
  '/match': typeof MatchRoute
  '/profile': typeof ProfileRoute
  '/result': typeof ResultRoute
  '/challenge/$code': typeof ChallengeCodeRoute
  '/play/dash': typeof PlayDashRoute
  '/play/direction': typeof PlayDirectionRoute
  '/play/flappy': typeof PlayFlappyRoute
  '/play/knife': typeof PlayKnifeRoute
  '/play/memory': typeof PlayMemoryRoute
  '/play/penalty': typeof PlayPenaltyRoute
  '/play/precision': typeof PlayPrecisionRoute
  '/play/reaction': typeof PlayReactionRoute
  '/play/rhythm': typeof PlayRhythmRoute
  '/play/stack': typeof PlayStackRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/games'
    | '/leaderboard'
    | '/match'
    | '/profile'
    | '/result'
    | '/challenge/$code'
    | '/play/dash'
    | '/play/direction'
    | '/play/flappy'
    | '/play/knife'
    | '/play/memory'
    | '/play/penalty'
    | '/play/precision'
    | '/play/reaction'
    | '/play/rhythm'
    | '/play/stack'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/games'
    | '/leaderboard'
    | '/match'
    | '/profile'
    | '/result'
    | '/challenge/$code'
    | '/play/dash'
    | '/play/direction'
    | '/play/flappy'
    | '/play/knife'
    | '/play/memory'
    | '/play/penalty'
    | '/play/precision'
    | '/play/reaction'
    | '/play/rhythm'
    | '/play/stack'
  id:
    | '__root__'
    | '/'
    | '/games'
    | '/leaderboard'
    | '/match'
    | '/profile'
    | '/result'
    | '/challenge/$code'
    | '/play/dash'
    | '/play/direction'
    | '/play/flappy'
    | '/play/knife'
    | '/play/memory'
    | '/play/penalty'
    | '/play/precision'
    | '/play/reaction'
    | '/play/rhythm'
    | '/play/stack'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  GamesRoute: typeof GamesRoute
  LeaderboardRoute: typeof LeaderboardRoute
  MatchRoute: typeof MatchRoute
  ProfileRoute: typeof ProfileRoute
  ResultRoute: typeof ResultRoute
  ChallengeCodeRoute: typeof ChallengeCodeRoute
  PlayDashRoute: typeof PlayDashRoute
  PlayDirectionRoute: typeof PlayDirectionRoute
  PlayFlappyRoute: typeof PlayFlappyRoute
  PlayKnifeRoute: typeof PlayKnifeRoute
  PlayMemoryRoute: typeof PlayMemoryRoute
  PlayPenaltyRoute: typeof PlayPenaltyRoute
  PlayPrecisionRoute: typeof PlayPrecisionRoute
  PlayReactionRoute: typeof PlayReactionRoute
  PlayRhythmRoute: typeof PlayRhythmRoute
  PlayStackRoute: typeof PlayStackRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/games': {
      id: '/games'
      path: '/games'
      fullPath: '/games'
      preLoaderRoute: typeof GamesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/match': {
      id: '/match'
      path: '/match'
      fullPath: '/match'
      preLoaderRoute: typeof MatchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result': {
      id: '/result'
      path: '/result'
      fullPath: '/result'
      preLoaderRoute: typeof ResultRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/challenge/$code': {
      id: '/challenge/$code'
      path: '/challenge/$code'
      fullPath: '/challenge/$code'
      preLoaderRoute: typeof ChallengeCodeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/dash': {
      id: '/play/dash'
      path: '/play/dash'
      fullPath: '/play/dash'
      preLoaderRoute: typeof PlayDashRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/direction': {
      id: '/play/direction'
      path: '/play/direction'
      fullPath: '/play/direction'
      preLoaderRoute: typeof PlayDirectionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/flappy': {
      id: '/play/flappy'
      path: '/play/flappy'
      fullPath: '/play/flappy'
      preLoaderRoute: typeof PlayFlappyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/knife': {
      id: '/play/knife'
      path: '/play/knife'
      fullPath: '/play/knife'
      preLoaderRoute: typeof PlayKnifeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/memory': {
      id: '/play/memory'
      path: '/play/memory'
      fullPath: '/play/memory'
      preLoaderRoute: typeof PlayMemoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/penalty': {
      id: '/play/penalty'
      path: '/play/penalty'
      fullPath: '/play/penalty'
      preLoaderRoute: typeof PlayPenaltyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/precision': {
      id: '/play/precision'
      path: '/play/precision'
      fullPath: '/play/precision'
      preLoaderRoute: typeof PlayPrecisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/reaction': {
      id: '/play/reaction'
      path: '/play/reaction'
      fullPath: '/play/reaction'
      preLoaderRoute: typeof PlayReactionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/rhythm': {
      id: '/play/rhythm'
      path: '/play/rhythm'
      fullPath: '/play/rhythm'
      preLoaderRoute: typeof PlayRhythmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/play/stack': {
      id: '/play/stack'
      path: '/play/stack'
      fullPath: '/play/stack'
      preLoaderRoute: typeof PlayStackRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  GamesRoute: GamesRoute,
  LeaderboardRoute: LeaderboardRoute,
  MatchRoute: MatchRoute,
  ProfileRoute: ProfileRoute,
  ResultRoute: ResultRoute,
  ChallengeCodeRoute: ChallengeCodeRoute,
  PlayDashRoute: PlayDashRoute,
  PlayDirectionRoute: PlayDirectionRoute,
  PlayFlappyRoute: PlayFlappyRoute,
  PlayKnifeRoute: PlayKnifeRoute,
  PlayMemoryRoute: PlayMemoryRoute,
  PlayPenaltyRoute: PlayPenaltyRoute,
  PlayPrecisionRoute: PlayPrecisionRoute,
  PlayReactionRoute: PlayReactionRoute,
  PlayRhythmRoute: PlayRhythmRoute,
  PlayStackRoute: PlayStackRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
